### ISSUE TITLE
Unable to start the project

### ISSUE THREAD

**Issue by apopiidoru** [jlooper/nativescript-paint#2]
Hi,

I'm want to add undo and redo functionalities, but I can't get the project to start ... a lot of files, dependencies missing.

**Comment by jlooper** [comment]
Hi, I need more info. I’m currently using it in an app without issue. What error are you getting?

**Comment by apopiidoru** [comment]
No using it is the problem, I want to extend it's functionalities, I've cloned the repository and I can't start it locally.

**Comment by apopiidoru** [comment]
For eg. scripts/postclone.js from src/ is missing

**Comment by jlooper** [comment]
hi, it's odd, as this is a fork of the standard plugin seed. not sure how that file dropped off but I just re-committed it. I didn't even have it my local project. Let me know of other missing bits
