### ISSUE TITLE
Plugin does not work with NS7 and angular 10

### ISSUE THREAD

**Issue by MartinPenev** [jlooper/nativescript-paint#24]
I'm trying to use the plugin in NativeScript 7 and Angular 10 and I'm getting the following error:

Uncaught (in promise): TypeError: Class constructor View cannot be invoked without 'new'
TypeError: Class constructor View cannot be invoked without 'new'
at PaintPadBase [as constructor] (file: node_modules/nativescript-paint/paint.common.js:7:0)
at new PaintPad (file: node_modules/nativescript-paint/paint.ios.js:9:0)
at ViewUtil.createView (file: node_modules/@nativescript/angular/fesm2015/nativescript-angular.js:2554:0)
...

Can you please update the plugin to use es2017 as target, as that seems to be the issue with the new NativeScript according to this - https://github.com/NativeScript/NativeScript/issues/8757

### Which platform(s) does your issue occur on?
- iOS/Android/Both - Both
- iOS/Android versions - All
- emulator or device.  - All

### Please, tell us how to recreate the issue in as much detail as possible. 
Try to use the plugin with a sample project from NS7.

**Comment by jlooper** [comment]
hi, thank you for your comment; would you like to PR the repo with that fix, as I haven't worked in the NativeScript space for a year now

**Comment by MartinPenev** [comment]
Here you go - https://github.com/jlooper/nativescript-paint/pull/25

Unfortunately, I had to update all the demos with the latest hello world template projects as there is a major breaking change between NS6 and NS7, hence the PR is quite big. The actual plugin change is only in the first commit.

**Comment by jlooper** [comment]
thank you, just saw this and merged, sorry for the delay

**Comment by jlooper** [comment]
published as 2.1.0, thank you again!
